# Site settings
title: Digital health labs
description: Your Site Description
theme: jekyll-theme-minimal

# Build settings
markdown: kramdown
permalink: pretty

# Additional settings
author:
  name: compelling works
  email: your@email.com

# Plugins
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme